// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.14.0
// source: dto.proto

package dto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GreetingService_Greeting_FullMethodName              = "/GreetingService/Greeting"
	GreetingService_LotsOfGreetingReplies_FullMethodName = "/GreetingService/LotsOfGreetingReplies"
)

// GreetingServiceClient is the client API for GreetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetingServiceClient interface {
	Greeting(ctx context.Context, in *GreetingServiceRequest, opts ...grpc.CallOption) (*GreetingServiceReply, error)
	LotsOfGreetingReplies(ctx context.Context, in *GreetingServiceRequest, opts ...grpc.CallOption) (GreetingService_LotsOfGreetingRepliesClient, error)
}

type greetingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetingServiceClient(cc grpc.ClientConnInterface) GreetingServiceClient {
	return &greetingServiceClient{cc}
}

func (c *greetingServiceClient) Greeting(ctx context.Context, in *GreetingServiceRequest, opts ...grpc.CallOption) (*GreetingServiceReply, error) {
	out := new(GreetingServiceReply)
	err := c.cc.Invoke(ctx, GreetingService_Greeting_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetingServiceClient) LotsOfGreetingReplies(ctx context.Context, in *GreetingServiceRequest, opts ...grpc.CallOption) (GreetingService_LotsOfGreetingRepliesClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetingService_ServiceDesc.Streams[0], GreetingService_LotsOfGreetingReplies_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greetingServiceLotsOfGreetingRepliesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetingService_LotsOfGreetingRepliesClient interface {
	Recv() (*GreetingServiceReply, error)
	grpc.ClientStream
}

type greetingServiceLotsOfGreetingRepliesClient struct {
	grpc.ClientStream
}

func (x *greetingServiceLotsOfGreetingRepliesClient) Recv() (*GreetingServiceReply, error) {
	m := new(GreetingServiceReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetingServiceServer is the server API for GreetingService service.
// All implementations must embed UnimplementedGreetingServiceServer
// for forward compatibility
type GreetingServiceServer interface {
	Greeting(context.Context, *GreetingServiceRequest) (*GreetingServiceReply, error)
	LotsOfGreetingReplies(*GreetingServiceRequest, GreetingService_LotsOfGreetingRepliesServer) error
	mustEmbedUnimplementedGreetingServiceServer()
}

// UnimplementedGreetingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreetingServiceServer struct {
}

func (UnimplementedGreetingServiceServer) Greeting(context.Context, *GreetingServiceRequest) (*GreetingServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greeting not implemented")
}
func (UnimplementedGreetingServiceServer) LotsOfGreetingReplies(*GreetingServiceRequest, GreetingService_LotsOfGreetingRepliesServer) error {
	return status.Errorf(codes.Unimplemented, "method LotsOfGreetingReplies not implemented")
}
func (UnimplementedGreetingServiceServer) mustEmbedUnimplementedGreetingServiceServer() {}

// UnsafeGreetingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetingServiceServer will
// result in compilation errors.
type UnsafeGreetingServiceServer interface {
	mustEmbedUnimplementedGreetingServiceServer()
}

func RegisterGreetingServiceServer(s grpc.ServiceRegistrar, srv GreetingServiceServer) {
	s.RegisterService(&GreetingService_ServiceDesc, srv)
}

func _GreetingService_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServiceServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetingService_Greeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServiceServer).Greeting(ctx, req.(*GreetingServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetingService_LotsOfGreetingReplies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetingServiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetingServiceServer).LotsOfGreetingReplies(m, &greetingServiceLotsOfGreetingRepliesServer{stream})
}

type GreetingService_LotsOfGreetingRepliesServer interface {
	Send(*GreetingServiceReply) error
	grpc.ServerStream
}

type greetingServiceLotsOfGreetingRepliesServer struct {
	grpc.ServerStream
}

func (x *greetingServiceLotsOfGreetingRepliesServer) Send(m *GreetingServiceReply) error {
	return x.ServerStream.SendMsg(m)
}

// GreetingService_ServiceDesc is the grpc.ServiceDesc for GreetingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GreetingService",
	HandlerType: (*GreetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _GreetingService_Greeting_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LotsOfGreetingReplies",
			Handler:       _GreetingService_LotsOfGreetingReplies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dto.proto",
}
